Updated default data and log directories for EN (#2192)
- the default data and log directories requires sudo privilege. the
fixed directory for data and log under the root of the package are
added.

diff --git a/build/packaging/linux/bin/kcnd b/build/packaging/linux/bin/kcnd
--- a/build/packaging/linux/bin/kcnd
+++ b/build/packaging/linux/bin/kcnd
@@ -6,8 +6,16 @@ CONF=$CMD_HOME/conf
 
 source $CONF/kcnd.conf
 
+if [ -z $DATA_DIR ]; then
+    echo
+    echo "  [ERROR] : DATA_DIR in conf/kcnd.conf is not defined."
+    exit 1
+fi
+
 if [ ! -d $DATA_DIR ]; then
-    mkdir -p $DATA_DIR
+    echo
+    echo "  [ERROR] : Genesis block is not initiated: [conf/kcnd.conf - DATA_DIR=$DATA_DIR]"
+    exit 1
 fi
 
 pidfile=$DATA_DIR/kcnd.pid
@@ -29,12 +37,6 @@ start() {
 
     echo -n "Starting kcnd: "
     
-    if [ ! -d $DATA_DIR ]; then
-        echo 
-        echo "  [ERROR] : kcnd is not initiated, Initiate kcnd with genesis file first."
-        exit 1
-    fi
-
     if [ ! -d $LOG_DIR ]; then
         mkdir -p $LOG_DIR
     fi
diff --git a/build/packaging/linux/bin/kend b/build/packaging/linux/bin/kend
--- a/build/packaging/linux/bin/kend
+++ b/build/packaging/linux/bin/kend
@@ -6,8 +6,16 @@ CONF=$CMD_HOME/conf
 
 source $CONF/kend.conf
 
+if [ -z $DATA_DIR ]; then
+    echo
+    echo "  [ERROR] : DATA_DIR in conf/kend.conf is not defined."
+    exit 1
+fi
+
 if [ ! -d $DATA_DIR ]; then
-    mkdir -p $DATA_DIR
+    echo
+    echo "  [ERROR] : Genesis block is not initiated: [conf/kend.conf - DATA_DIR=$DATA_DIR]"
+    exit 1
 fi
 
 pidfile=$DATA_DIR/kend.pid
@@ -28,12 +36,6 @@ start() {
     [ -n "$pid" ] && echo "kend already running...[$pid]" && return
 
     echo -n "Starting kend: "
-    
-    if [ ! -d $DATA_DIR ]; then
-        echo 
-        echo "  [ERROR] : kend is not initiated, Initiate kend with genesis file first."
-        exit 1
-    fi
 
     if [ ! -d $LOG_DIR ]; then
         mkdir -p $LOG_DIR
diff --git a/build/packaging/linux/bin/kpnd b/build/packaging/linux/bin/kpnd
--- a/build/packaging/linux/bin/kpnd
+++ b/build/packaging/linux/bin/kpnd
@@ -6,8 +6,16 @@ CONF=$CMD_HOME/conf
 
 source $CONF/kpnd.conf
 
+if [ -z $DATA_DIR ]; then
+    echo
+    echo "  [ERROR] : DATA_DIR in conf/kpnd.conf is not defined."
+    exit 1
+fi
+
 if [ ! -d $DATA_DIR ]; then
-    mkdir -p $DATA_DIR
+    echo
+    echo "  [ERROR] : Genesis block is not initiated: [conf/kpnd.conf - DATA_DIR=$DATA_DIR]"
+    exit 1
 fi
 
 pidfile=$DATA_DIR/kpnd.pid
@@ -28,12 +36,6 @@ start() {
     [ -n "$pid" ] && echo "kpnd already running...[$pid]" && return
 
     echo -n "Starting kpnd: "
-    
-    if [ ! -d $DATA_DIR ]; then
-        echo 
-        echo "  [ERROR] : kpnd is not initiated, Initiate kpnd with genesis file first."
-        exit 1
-    fi
 
     if [ ! -d $LOG_DIR ]; then
         mkdir -p $LOG_DIR
